language: go
go:
  - "1.12"

env:
  - GO111MODULE=on

install: true

jobs:
  include:
    - stage: test
      script:
        - make test
    - stage: build image
      script:
        - ./image.sh build
      after_success:
        - if [[ "${TRAVIS_BRANCH}" = "master" ]] && [[ "${TRAVIS_PULL_REQUEST}" = "false" ]]; then
          ./image.sh push;
          fi
